assert if test fails to return to original branch during cleanup

diff --git a/tests/ship_on_branch_with_untracked_files b/tests/ship_on_branch_with_untracked_files
--- a/tests/ship_on_branch_with_untracked_files
+++ b/tests/ship_on_branch_with_untracked_files
@@ -14,7 +14,12 @@ output="$(scripts/ship.sh -t)"
 
 # cleanup
 rm -f temp.txt
-git checkout ${CURRENT} >& /dev/null
+git checkout $CURRENT >& /dev/null
+if [ "${CURRENT}" != "$(git branch | grep '\*' | awk '{print $2}')" ]
+then
+	echo "ERROR: 'git checkout $CURRENT' failed to return to original branch."
+	exit 1
+fi
 git branch -d ${branch} >& /dev/null
 
 # verify
diff --git a/tests/ship_on_master_with_unstaged_changes b/tests/ship_on_master_with_unstaged_changes
--- a/tests/ship_on_master_with_unstaged_changes
+++ b/tests/ship_on_master_with_unstaged_changes
@@ -8,7 +8,12 @@ output="$(scripts/ship.sh -t 2>&1)"
 
 # cleanup
 git checkout README.md
-git checkout ${CURRENT} >& /dev/null
+git checkout $CURRENT >& /dev/null
+if [ "${CURRENT}" != "$(git branch | grep '\*' | awk '{print $2}')" ]
+then
+	echo "ERROR: 'git checkout $CURRENT' failed to return to original branch."
+	exit 1
+fi
 
 # verify
 result="$(echo ${output} | grep 'should be run from a feature branch')"
