test hygiene

diff --git a/tests/ship_on_branch_with_untracked_files b/tests/ship_on_branch_with_untracked_files
--- a/tests/ship_on_branch_with_untracked_files
+++ b/tests/ship_on_branch_with_untracked_files
@@ -1,6 +1,6 @@
 # setup
 CURRENT="$(git branch | grep '\*' | awk '{print $2}')"
-branch="${CURRENT}_temp"
+branch="temp"
 git checkout -b "${branch}" >& /dev/null
 touch temp.txt
 if [ ! -e "temp.txt" ]
@@ -20,13 +20,22 @@ then
 	echo "ERROR: 'git checkout $CURRENT' failed to return to original branch."
 	exit 1
 fi
-git branch -d ${branch} >& /dev/null
+git branch -D ${branch} >& /dev/null
 
-# verify
+# verify was run from branch
+result="$(echo ${output} | grep 'current branch is: temp')"
+# report
+if [ -z "$result" ]
+then
+	printf "%-50s FAIL\n\tDid not run on branch '${branch}'\n\n${output}\n${result}\n" "$0"
+	exit 1
+fi
+
+# verify found correct remote branch
 result="$(echo ${output} | grep 'test complete')"
 
 # report
-if [ "$result" != "" ]
+if [ ! -z "$result" ]
 then
 	printf "%-50s PASS\n" "$0"
 	exit 0
diff --git a/tests/ship_on_branch_with_updated_master_can_determine_remote_name b/tests/ship_on_branch_with_updated_master_can_determine_remote_name
--- a/tests/ship_on_branch_with_updated_master_can_determine_remote_name
+++ b/tests/ship_on_branch_with_updated_master_can_determine_remote_name
@@ -1,9 +1,11 @@
 # setup
 CURRENT="$(git branch | grep '\*' | awk '{print $2}')"
+branch="temp"
+git checkout -b "${branch}" >& /dev/null
 git checkout master >& /dev/null
 gitCommit="$(git rev-parse HEAD)"
 git commit --allow-empty -m "test commit on master" >& /dev/null
-git checkout ${CURRENT} >& /dev/null
+git checkout ${branch} >& /dev/null
 
 # try
 output="$(scripts/ship.sh -t)"
@@ -24,12 +26,22 @@ then
 	echo "ERROR: 'git checkout $CURRENT' failed to return to original branch."
 	exit 1
 fi
+git branch -D ${branch} >& /dev/null
 
-# verify
+# verify was run from branch
+result="$(echo ${output} | grep 'current branch is: temp')"
+# report
+if [ -z "$result" ]
+then
+	printf "%-50s FAIL\n\tDid not run on branch '${branch}'\n\n${output}\n${result}\n" "$0"
+	exit 1
+fi
+
+# verify found correct remote branch
 result="$(echo ${output} | grep 'remote branch is: master')"
 
 # report
-if [ "$result" != "" ]
+if [ ! -z "$result" ]
 then
 	printf "%-50s PASS\n" "$0"
 	exit 0
